#pragma once

#define INSERE_REGISTRO 'i'
#define CONSULTA_SIMPLES 'c'
#define CONSULTA_POR_FAIXA_DE_NOMES_DE_AUTORES 'n'
#define CONSULTA_POR_FAIXA_DE_ANOS 'a'
#define CONSULTA_POR_FAIXA_DE_NOMES_DE_AUTORES_E_ANOS 'q'
#define IMPRIME_INDICE_DA_ARVORE 't'
#define IMPRIME_PAGINA 'p'
#define TERMINO_DA_SEQUENCIA_DE_COMANDOS 'e'